version: "3"
services:
  database:
    image: "postgres"
    container_name: database
    environment:
      POSTGRES_USER: books_user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: books_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"